CodetoCountry = {
 "AFG": "Afghanistan",
 "ALB": "Albania",
 "DZA": "Algeria",
 "ASM": "American Samoa",
 "AND": "Andorra",
 "AGO": "Angola",
 "AIA": "Anguilla",
 "ATG": "Antigua and Barbuda",
 "ARG": "Argentina",
 "ARM": "Armenia",
 "ABW": "Aruba",
 "AUS": "Australia",
 "AUT": "Austria",
 "AZE": "Azerbaijan",
 "BHS": "Bahamas",
 "BHR": "Bahrain",
 "BGD": "Bangladesh",
 "BRB": "Barbados",
 "BLR": "Belarus",
 "BEL": "Belgium",
 "BLZ": "Belize",
 "BEN": "Benin",
 "BMU": "Bermuda",
 "BTN": "Bhutan",
 "BOL": "Bolivia",
 "BIH": "Bosnia and Herzegovina",
 "BWA": "Botswana",
 "BRA": "Brazil",
 "VGB": "British Virgin Islands",
 "BRN": "Brunei Darussalam",
 "BGR": "Bulgaria",
 "BFA": "Burkina Faso",
 "BDI": "Burundi",
 "KHM": "Cambodia",
 "CMR": "Cameroon",
 "CAN": "Canada",
 "CPV": "Cape Verde",
 "CYM": "Cayman Islands",
 "CAF": "Central African Republic",
 "TCD": "Chad",
 "CHL": "Chile",
 "CHN": "China",
 "COL": "Colombia",
 "COM": "Comoros",
 "COG": "Congo",
 "COK": "Cook Islands",
 "CRI": "Costa Rica",
 "CIV": "Côte d\"Ivoire",
 "HRV": "Croatia",
 "CUB": "Cuba",
 "CYP": "Cyprus",
 "CZE": "Czech Republic",
 "PRK": "Democratic People\"s Republic of Korea",
 "COD": "Democratic Republic of the Congo",
 "DNK": "Denmark",
 "DJI": "Djibouti",
 "DMA": "Dominica",
 "DOM": "Dominican Republic",
 "TMP": "East Timor",
 "ECU": "Ecuador",
 "EGY": "Egypt",
 "SLV": "El Salvador",
 "GNQ": "Equatorial Guinea",
 "ERI": "Eritrea",
 "EST": "Estonia",
 "ETH": "Ethiopia",
 "FRO": "Faeroe Islands",
 "FLK": "Falkland Islands [Malvinas]",
 "FSM": "Micronesia",
 "FJI": "Fiji",
 "FIN": "Finland",
 "MKD": "The former Yugoslav Republic of Macedonia",
 "FRA": "France",
 "GUF": "French Guiana",
 "PYF": "French Polynesia",
 "GAB": "Gabon",
 "GMB": "Gambia",
 "GEO": "Georgia",
 "DEU": "Germany",
 "GHA": "Ghana",
 "GIB": "Gibraltar",
 "GRC": "Greece",
 "GRL": "Greenland",
 "GRD": "Grenada",
 "GLP": "Guadeloupe",
 "GUM": "Guam",
 "GTM": "Guatemala",
 "GIN": "Guinea",
 "GNB": "Guinea-Bissau",
 "GUY": "Guyana",
 "HTI": "Haiti",
 "VAT": "Holy See",
 "HND": "Honduras",
 "HKG": "Hong Kong Special Administrative Region of China",
 "HUN": "Hungary",
 "ISL": "Iceland",
 "IND": "India",
 "IDN": "Indonesia",
 "IRN": "Iran [Islamic Republic of]",
 "IRQ": "Iraq",
 "IRL": "Ireland",
 "IMY": "Isle of Man",
 "ISR": "Israel",
 "ITA": "Italy",
 "JAM": "Jamaica",
 "JPN": "Japan",
 "JOR": "Jordan",
 "KAZ": "Kazakhstan",
 "KEN": "Kenya",
 "KIR": "Kiribati",
 "KWT": "Kuwait",
 "KGZ": "Kyrgyzstan",
 "LAO": "Lao People\"s Democratic Republic",
 "LVA": "Latvia",
 "LBN": "Lebanon",
 "LSO": "Lesotho",
 "LBR": "Liberia",
 "LBY": "Libyan Arab Jamahiriya",
 "LIE": "Liechtenstein",
 "LTU": "Lithuania",
 "LUX": "Luxembourg",
 "MAC": "Macau",
 "MDG": "Madagascar",
 "MWI": "Malawi",
 "MYS": "Malaysia",
 "MDV": "Maldives",
 "MLI": "Mali",
 "MLT": "Malta",
 "MHL": "Marshall Islands",
 "MTQ": "Martinique",
 "MRT": "Mauritania",
 "MUS": "Mauritius",
 "MEX": "Mexico",
 "MCO": "Monaco",
 "MNG": "Mongolia",
 "MSR": "Montserrat",
 "MAR": "Morocco",
 "MOZ": "Mozambique",
 "MMR": "Myanmar",
 "NAM": "Namibia",
 "NRU": "Nauru",
 "NPL": "Nepal",
 "NLD": "Netherlands",
 "ANT": "Netherlands Antilles",
 "NCL": "New Caledonia",
 "NZL": "New Zealand",
 "NIC": "Nicaragua",
 "NER": "Niger",
 "NGA": "Nigeria",
 "NIU": "Niue",
 "NFK": "Norfolk Island",
 "MNP": "Northern Mariana Islands",
 "NOR": "Norway",
 "PSE": "Occupied Palestinian Territory",
 "OMN": "Oman",
 "PAK": "Pakistan",
 "PLW": "Palau",
 "PAN": "Panama",
 "PNG": "Papua New Guinea",
 "PRY": "Paraguay",
 "PER": "Peru",
 "PHL": "Philippines",
 "PCN": "Pitcairn",
 "POL": "Poland",
 "PRT": "Portugal",
 "PRI": "Puerto Rico",
 "QAT": "Qatar",
 "KOR": "Republic of Korea",
 "MDA": "Republic of Moldova",
 "ROM": "Romania",
 "REU": "Réunion",
 "RUS": "Russian Federation",
 "RWA": "Rwanda",
 "SHN": "Saint Helena",
 "KNA": "Saint Kitts and Nevis",
 "LCA": "Saint Lucia",
 "SPM": "Saint Pierre and Miquelon",
 "VCT": "Saint Vincent and the Grenadines",
 "WSM": "Samoa",
 "SMR": "San Marino",
 "STP": "Sao Tome and Principe",
 "SAU": "Saudi Arabia",
 "SEN": "Senegal",
 "SYC": "Seychelles",
 "SLE": "Sierra Leone",
 "SGP": "Singapore",
 "SVK": "Slovakia",
 "SVN": "Slovenia",
 "SLB": "Solomon Islands",
 "SOM": "Somalia",
 "ZAF": "South Africa",
 "ESP": "Spain",
 "LKA": "Sri Lanka",
 "SDN": "Sudan",
 "SUR": "Suriname",
 "SJM": "Svalbard and Jan Mayen Islands",
 "SWZ": "Swaziland",
 "SWE": "Sweden",
 "CHE": "Switzerland",
 "SYR": "Syrian Arab Republic",
 "TWN": "Taiwan Province of China",
 "TJK": "Tajikistan",
 "THA": "Thailand",
 "TGO": "Togo",
 "TKL": "Tokelau",
 "TON": "Tonga",
 "TTO": "Trinidad and Tobago",
 "TUN": "Tunisia",
 "TUR": "Turkey",
 "TKM": "Turkmenistan",
 "TCA": "Turks and Caicos Islands",
 "TUV": "Tuvalu",
 "UGA": "Uganda",
 "UKR": "Ukraine",
 "ARE": "United Arab Emirates",
 "GBR": "United Kingdom",
 "TZA": "United Republic of Tanzania",
 "USA": "United States",
 "VIR": "United States Virgin Islands",
 "URY": "Uruguay",
 "UZB": "Uzbekistan",
 "VUT": "Vanuatu",
 "VEN": "Venezuela",
 "VNM": "Viet Nam",
 "WLF": "Wallis and Futuna Islands",
 "ESH": "Western Sahara",
 "YEM": "Yemen",
 "YUG": "Yugoslavia",
 "ZMB": "Zambia",
 "ZWE": "Zimbabwe"
};
CountrytoCode={
      "Afghanistan"                                         :    "AFG",
  "Albania"                                             :    "ALB",
  "Algeria"                                             :    "DZA",
  "American Samoa"                                      :    "ASM",
  "Andorra"                                             :    "AND",
  "Angola"                                              :    "AGO",
  "Anguilla"                                            :    "AIA",
  "Antigua and Barbuda"                                 :    "ATG",
  "Argentina"                                           :    "ARG",
  "Armenia"                                             :    "ARM",
  "Aruba"                                               :    "ABW",
  "Australia"                                           :    "AUS",
  "Austria"                                             :    "AUT",
  "Azerbaijan"                                          :    "AZE",
  "Bahamas"                                             :    "BHS",
  "Bahrain"                                             :    "BHR",
  "Bangladesh"                                          :    "BGD",
  "Barbados"                                            :    "BRB",
  "Belarus"                                             :    "BLR",
  "Belgium"                                             :    "BEL",
  "Belize"                                              :    "BLZ",
  "Benin"                                               :    "BEN",
  "Bermuda"                                             :    "BMU",
  "Bhutan"                                              :    "BTN",
  "Bolivia"                                             :    "BOL",
  "Bosnia and Herzegovina"                              :    "BIH",
  "Botswana"                                            :    "BWA",
  "Brazil"                                              :    "BRA",
  "British Virgin Islands"                              :    "VGB",
  "Brunei Darussalam"                                   :    "BRN",
  "Bulgaria"                                            :    "BGR",
  "Burkina Faso"                                        :    "BFA",
  "Burundi"                                             :    "BDI",
  "Cambodia"                                            :    "KHM",
  "Cameroon"                                            :    "CMR",
  "Canada"                                              :    "CAN",
  "Cape Verde"                                          :    "CPV",
  "Cayman Islands"                                      :    "CYM",
  "Central African Republic"                            :    "CAF",
  "Chad"                                                :    "TCD",
  "Chile"                                               :    "CHL",
  "China"                                               :    "CHN",
  "Colombia"                                            :    "COL",
  "Comoros"                                             :    "COM",
  "Congo"                                               :    "COG",
  "Cook Islands"                                        :    "COK",
  "Costa Rica"                                          :    "CRI",
  "Côte d\"Ivoire"                                      :    "CIV",
  "Croatia"                                             :    "HRV",
  "Cuba"                                                :    "CUB",
  "Cyprus"                                              :    "CYP",
  "Czech Republic"                                      :    "CZE",
  "Democratic People\"s Republic of Korea"              :    "PRK",
  "Democratic Republic of the Congo"                    :    "COD",
  "Denmark"                                             :    "DNK",
  "Djibouti"                                            :    "DJI",
  "Dominica"                                            :    "DMA",
  "Dominican Republic"                                  :    "DOM",
  "East Timor"                                          :    "TMP",
  "Ecuador"                                             :    "ECU",
  "Egypt"                                               :    "EGY",
  "El Salvador"                                         :    "SLV",
  "Equatorial Guinea"                                   :    "GNQ",
  "Eritrea"                                             :    "ERI",
  "Estonia"                                             :    "EST",
  "Ethiopia"                                            :    "ETH",
  "Faeroe Islands"                                      :    "FRO",
  "Falkland Islands [Malvinas]"                         :    "FLK",
  "Micronesia"                                          :    "FSM",
  "Fiji"                                                :    "FJI",
  "Finland"                                             :    "FIN",
  "The former Yugoslav Republic of Macedonia"           :    "MKD",
  "France"                                              :    "FRA",
  "French Guiana"                                       :    "GUF",
  "French Polynesia"                                    :    "PYF",
  "Gabon"                                               :    "GAB",
  "Gambia"                                              :    "GMB",
  "Georgia"                                             :    "GEO",
  "Germany"                                             :    "DEU",
  "Ghana"                                               :    "GHA",
  "Gibraltar"                                           :    "GIB",
  "Greece"                                              :    "GRC",
  "Greenland"                                           :    "GRL",
  "Grenada"                                             :    "GRD",
  "Guadeloupe"                                          :    "GLP",
  "Guam"                                                :    "GUM",
  "Guatemala"                                           :    "GTM",
  "Guinea"                                              :    "GIN",
  "Guinea-Bissau"                                       :    "GNB",
  "Guyana"                                              :    "GUY",
  "Haiti"                                               :    "HTI",
  "Holy See"                                            :    "VAT",
  "Honduras"                                            :    "HND",
  "Hong Kong Special Administrative Region of China"    :    "HKG",
  "Hungary"                                             :    "HUN",
  "Iceland"                                             :    "ISL",
  "India"                                               :    "IND",
  "Indonesia"                                           :    "IDN",
  "Iran [Islamic Republic of]"                          :    "IRN",
  "Iraq"                                                :    "IRQ",
  "Ireland"                                             :    "IRL",
  "Isle of Man"                                         :    "IMY",
  "Israel"                                              :    "ISR",
  "Italy"                                               :    "ITA",
  "Jamaica"                                             :    "JAM",
  "Japan"                                               :    "JPN",
  "Jordan"                                              :    "JOR",
  "Kazakhstan"                                          :    "KAZ",
  "Kenya"                                               :    "KEN",
  "Kiribati"                                            :    "KIR",
  "Kuwait"                                              :    "KWT",
  "Kyrgyzstan"                                          :    "KGZ",
  "Lao People\"s Democratic Republic"                   :    "LAO",
  "Latvia"                                              :    "LVA",
  "Lebanon"                                             :    "LBN",
  "Lesotho"                                             :    "LSO",
  "Liberia"                                             :    "LBR",
  "Libyan Arab Jamahiriya"                              :    "LBY",
  "Liechtenstein"                                       :    "LIE",
  "Lithuania"                                           :    "LTU",
  "Luxembourg"                                          :    "LUX",
  "Macau"                                               :    "MAC",
  "Madagascar"                                          :    "MDG",
  "Malawi"                                              :    "MWI",
  "Malaysia"                                            :    "MYS",
  "Maldives"                                            :    "MDV",
  "Mali"                                                :    "MLI",
  "Malta"                                               :    "MLT",
  "Marshall Islands"                                    :    "MHL",
  "Martinique"                                          :    "MTQ",
  "Mauritania"                                          :    "MRT",
  "Mauritius"                                           :    "MUS",
  "Mexico"                                              :    "MEX",
  "Monaco"                                              :    "MCO",
  "Mongolia"                                            :    "MNG",
  "Montserrat"                                          :    "MSR",
  "Morocco"                                             :    "MAR",
  "Mozambique"                                          :    "MOZ",
  "Myanmar"                                             :    "MMR",
  "Namibia"                                             :    "NAM",
  "Nauru"                                               :    "NRU",
  "Nepal"                                               :    "NPL",
  "Netherlands"                                         :    "NLD",
  "Netherlands Antilles"                                :    "ANT",
  "New Caledonia"                                       :    "NCL",
  "New Zealand"                                         :    "NZL",
  "Nicaragua"                                           :    "NIC",
  "Niger"                                               :    "NER",
  "Nigeria"                                             :    "NGA",
  "Niue"                                                :    "NIU",
  "Norfolk Island"                                      :    "NFK",
  "Northern Mariana Islands"                            :    "MNP",
  "Norway"                                              :    "NOR",
  "Occupied Palestinian Territory"                      :    "PSE",
  "Oman"                                                :    "OMN",
  "Pakistan"                                            :    "PAK",
  "Palau"                                               :    "PLW",
  "Panama"                                              :    "PAN",
  "Papua New Guinea"                                    :    "PNG",
  "Paraguay"                                            :    "PRY",
  "Peru"                                                :    "PER",
  "Philippines"                                         :    "PHL",
  "Pitcairn"                                            :    "PCN",
  "Poland"                                              :    "POL",
  "Portugal"                                            :    "PRT",
  "Puerto Rico"                                         :    "PRI",
  "Qatar"                                               :    "QAT",
  "Republic of Korea"                                   :    "KOR",
  "Republic of Moldova"                                 :    "MDA",
  "Romania"                                             :    "ROM",
  "Réunion"                                             :    "REU",
  "Russian Federation"                                  :    "RUS",
  "Rwanda"                                              :    "RWA",
  "Saint Helena"                                        :    "SHN",
  "Saint Kitts and Nevis"                               :    "KNA",
  "Saint Lucia"                                         :    "LCA",
  "Saint Pierre and Miquelon"                           :    "SPM",
  "Saint Vincent and the Grenadines"                    :    "VCT",
  "Samoa"                                               :    "WSM",
  "San Marino"                                          :    "SMR",
  "Sao Tome and Principe"                               :    "STP",
  "Saudi Arabia"                                        :    "SAU",
  "Senegal"                                             :    "SEN",
  "Seychelles"                                          :    "SYC",
  "Sierra Leone"                                        :    "SLE",
  "Singapore"                                           :    "SGP",
  "Slovakia"                                            :    "SVK",
  "Slovenia"                                            :    "SVN",
  "Solomon Islands"                                     :    "SLB",
  "Somalia"                                             :    "SOM",
  "South Africa"                                        :    "ZAF",
  "Spain"                                               :    "ESP",
  "Sri Lanka"                                           :    "LKA",
  "Sudan"                                               :    "SDN",
  "Suriname"                                            :    "SUR",
  "Svalbard and Jan Mayen Islands"                      :    "SJM",
  "Swaziland"                                           :    "SWZ",
  "Sweden"                                              :    "SWE",
  "Switzerland"                                         :    "CHE",
  "Syrian Arab Republic"                                :    "SYR",
  "Taiwan Province of China"                            :    "TWN",
  "Tajikistan"                                          :    "TJK",
  "Thailand"                                            :    "THA",
  "Togo"                                                :    "TGO",
  "Tokelau"                                             :    "TKL",
  "Tonga"                                               :    "TON",
  "Trinidad and Tobago"                                 :    "TTO",
  "Tunisia"                                             :    "TUN",
  "Turkey"                                              :    "TUR",
  "Turkmenistan"                                        :    "TKM",
  "Turks and Caicos Islands"                            :    "TCA",
  "Tuvalu"                                              :    "TUV",
  "Uganda"                                              :    "UGA",
  "Ukraine"                                             :    "UKR",
  "United Arab Emirates"                                :    "ARE",
  "United Kingdom"                                      :    "GBR",
  "United Republic of Tanzania"                         :    "TZA",
  "United States"                                       :    "USA",
  "United States Virgin Islands"                        :    "VIR",
  "Uruguay"                                             :    "URY",
  "Uzbekistan"                                          :    "UZB",
  "Vanuatu"                                             :    "VUT",
  "Venezuela"                                           :    "VEN",
  "Viet Nam"                                            :    "VNM",
  "Wallis and Futuna Islands"                           :    "WLF",
  "Western Sahara"                                      :    "ESH",
  "Yemen"                                               :    "YEM",
  "Yugoslavia"                                          :    "YUG",
  "Zambia"                                              :    "ZMB",
  "Zimbabwe"                                             :    "ZWE"
}
CodetoState = {
    "AL": "Alabama",
    "AK": "Alaska",
    "AS": "American Samoa",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "DC": "District Of Columbia",
    "FM": "Federated States Of Micronesia",
    "FL": "Florida",
    "GA": "Georgia",
    "GU": "Guam",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MH": "Marshall Islands",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "MP": "Northern Mariana Islands",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PW": "Palau",
    "PA": "Pennsylvania",
    "PR": "Puerto Rico",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VI": "Virgin Islands",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming"
}

StatetoCode={
             "Alabama"                          :       "AL",           
     "Alaska"                           :       "AK",           
     "American Samoa"                   :       "AS",           
     "Arizona"                          :       "AZ",           
     "Arkansas"                         :       "AR",           
     "California"                       :       "CA",           
     "Colorado"                         :       "CO",           
     "Connecticut"                      :       "CT",           
     "Delaware"                         :       "DE",           
     "District Of Columbia"             :       "DC",           
     "Federated States Of Micronesia"   :       "FM",           
     "Florida"                          :       "FL",           
     "Georgia"                          :       "GA",           
     "Guam"                             :       "GU",           
     "Hawaii"                           :       "HI",           
     "Idaho"                            :       "ID",           
     "Illinois"                         :       "IL",           
     "Indiana"                          :       "IN",           
     "Iowa"                             :       "IA",           
     "Kansas"                           :       "KS",           
     "Kentucky"                         :       "KY",           
     "Louisiana"                        :       "LA",           
     "Maine"                            :       "ME",           
     "Marshall Islands"                 :       "MH",           
     "Maryland"                         :       "MD",           
     "Massachusetts"                    :       "MA",           
     "Michigan"                         :       "MI",           
     "Minnesota"                        :       "MN",           
     "Mississippi"                      :       "MS",           
     "Missouri"                         :       "MO",           
     "Montana"                          :       "MT",           
     "Nebraska"                         :       "NE",           
     "Nevada"                           :       "NV",           
     "New Hampshire"                    :       "NH",           
     "New Jersey"                       :       "NJ",           
     "New Mexico"                       :       "NM",           
     "New York"                         :       "NY",           
     "North Carolina"                   :       "NC",           
     "North Dakota"                     :       "ND",           
     "Northern Mariana Islands"         :       "MP",           
     "Ohio"                             :       "OH",           
     "Oklahoma"                         :       "OK",           
     "Oregon"                           :       "OR",           
     "Palau"                            :       "PW",           
     "Pennsylvania"                     :       "PA",           
     "Puerto Rico"                      :       "PR",           
     "Rhode Island"                     :       "RI",           
     "South Carolina"                   :       "SC",           
     "South Dakota"                     :       "SD",           
     "Tennessee"                        :       "TN",           
     "Texas"                            :       "TX",           
     "Utah"                             :       "UT",           
     "Vermont"                          :       "VT",           
     "Virgin Islands"                   :       "VI",           
     "Virginia"                         :       "VA",           
     "Washington"                       :       "WA",           
     "West Virginia"                    :       "WV",           
     "Wisconsin"                        :       "WI",           
     "Wyoming"                           :       "WY"           

}